<!-- A div to contain the list of errors generated by JavaScript -->
<div id="errorList"></div>
<!-- Logo -->
<a href="<?=$webRoot?>" class="logo-link" title="Home">
	<img src="<?=$webRoot?>/media/img/logo.svg" alt="Quizinator" class="logo-img">
</a>